---
talons:
  driveLeft:
    deviceNumber: 1
    motorControllerType: TALON_FX
    type: BRUSHLESS
    subsystemName: Drive
    inverted: INVERTED
    statusFrame: STATUS_2
    followers:
      - id: 2
        motorControllerType: TALON_FX
        type: BRUSHLESS
        inverted: FollowMaster
    pidControllers:
      - p: 0
        i: 0
        d: 0
        f: 0
        maxVelocity: 18000
        maxAcceleration: 45000
        maxIntegralAccumulator: 0
        integralZone: 0
        allowableClosedLoopError: 0
  driveRight:
    deviceNumber: 3
    motorControllerType: TALON_FX
    type: BRUSHLESS
    subsystemName: Drive
    inverted: NONINVERTED
    statusFrame: STATUS_2
    followers:
      - id: 4
        motorControllerType: TALON_FX
        type: BRUSHLESS
        inverted: FollowMaster
    pidControllers:
      - p: 0
        i: 0
        d: 0
        f: 0
        maxVelocity: 18000
        maxAcceleration: 45000
        maxIntegralAccumulator: 0
        integralZone: 0
        allowableClosedLoopError: 0
  magazine:
    device number: 8
    motorControllerType: TALON_FX
    type: BRUSHLESS
    subsystemName: Magazine
    inverted: NONINVERTED
    statusFrame: STATUS_2
    followers:
      - id: 9
        motorControllerType: TALON_FX
        type: BRUSHLESS
        inverted: OpposeMaster
    pidControllers:
      - p: 0
        i: 0
        d: 0
        f: 0
        maxVelocity: 18000
        maxAcceleration: 45000
        maxIntegralAccumulator: 0
        integralZone: 0
        allowableClosedLoopError: 0