---
talons:
  driveLeft:
    deviceNumber: 2
    motorControllerType: TALON_FX
    type: BRUSHLESS
    subsystemName: Drive
    inverted: INVERTED
    statusFrame: STATUS_2
    followers:
      - id: 3
        motorControllerType: TALON_FX
        type: BRUSHLESS
        inverted: FollowMaster
    pidControllers:
      - p: 0
        i: 0
        d: 0
        f: 0
        maxVelocity: 18000
        maxAcceleration: 45000
        maxIntegralAccumulator: 0
        integralZone: 0
        allowableClosedLoopError: 0
  driveRight:
    deviceNumber: 4
    motorControllerType: TALON_FX
    type: BRUSHLESS
    subsystemName: Drive
    inverted: NONINVERTED
    statusFrame: STATUS_2
    followers:
      - id: 5
        motorControllerType: TALON_FX
        type: BRUSHLESS
        inverted: FollowMaster
    pidControllers:
      - p: 0
        i: 0
        d: 0
        f: 0
        maxVelocity: 18000
        maxAcceleration: 45000
        maxIntegralAccumulator: 0
        integralZone: 0
        allowableClosedLoopError: 0
  intake:
    deviceNumber: 6
    motorControllerType: TALON_FX
    type: BRUSHLESS
    subsystemName: Intake
    inverted: NONINVERTED
    statusFrame: STATUS_2
  flywheel:
    deviceNumber: 7
    motorControllerType: TALON_FX
    type: BRUSHLESS
    subsystemName: Shooter
    inverted: INVERTED
    statusFrame: STATUS_2
    followers:
      - id: 8
        motorControllerType: TALON_FX
        type: BRUSHLESS
        inverted: OpposeMaster
    pidControllers:
      - p: 0.75
        i: 0.00015
        d: 2.83125
        f: 0
        maxVelocity: 18000
        maxAcceleration: 45000
        maxIntegralAccumulator: 0
        integralZone: 0
        allowableClosedLoopError: 0
  magazine:
    deviceNumber: 9
    motorControllerType: TALON_FX
    type: BRUSHLESS
    subsystemName: Magazine
    inverted: INVERTED
    statusFrame: STATUS_2
    followers:
      - id: 10
        motorControllerType: TALON_FX
        type: BRUSHLESS
        inverted: OpposeMaster
  kicker:
    deviceNumber: 11
    motorControllerType: TALON_FX
    type: BRUSHLESS
    subsystemName: Magazine
    inverted: NONINVERTED
    statusFrame: STATUS_2
